language: go

go:
  - "1.11"

env:
  - DEP_VERSION="0.5.0" GO111MODULE="on" # I'm using 0.5.0, so Travis gets to use 0.5.0

before_install:
  # if we're in a mainline build, don't make a symlink
  # if we're not in a mainline build, symlink the proper dir to point to this dir.
  - if [["github.com/BlueK8S" in $(TRAVIS_BUILD_DIR)]]; then echo "mainline build, no symlink"; else mkdir -p $GOPATH/src/github.com/BlueK8S && ln -s $(pwd) $GOPATH/src/github.com/BlueK8S/kubedirector ; fi
  # Get dep
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - make dep

script:
  - make compile
  - bash -c "make verify-modules"
