apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: {{ .Values.appCrdName }}
  labels:
    app: {{ template "kubedirector.name" . }}
    chart: {{ template "kubedirector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  group: kubedirector.bluedata.io
  names:
    kind: KubeDirectorApp
    listKind: KubeDirectorAppList
    plural: kubedirectorapps
    singular: kubedirectorapp
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required: [label, distro_id, version, roles, config]
          properties:
            label:
              required: [name]
              properties:
                name:
                  type: string
                  minLength: 1
                description:
                  type: string
            distro_id:
              type: string
              minLength: 1
            version:
              type: string
              minLength: 1
            image:
              required: [repoTag]
              properties:
                repoTag:
                  type: string
                  minLength: 1
            setup_package:
              required: [config_api_version, import_url]
              properties:
                config_api_version:
                  type: integer
                  minimum: 7
                import_url:
                  type: string
                  pattern: '^https?://.+\.tgz$'
            services:
              type: array
              items:
                required: [id]
                properties:
                  id:
                    type: string
                    minLength: 1
                  label:
                    required: [name]
                    properties:
                      name:
                        type: string
                        minLength: 1
                      description:
                        type: string
                  endpoint:
                    required: [port]
                    properties:
                      port:
                        type: integer
                        minimum: 0
                      url_scheme:
                        type: string
                        minLength: 1
                      path:
                        type: string
                      is_dashboard:
                        type: boolean
            roles:
              type: array
              items:
                required: [id, cardinality]
                properties:
                  id:
                    type: string
                    minLength: 1
                  cardinality:
                    type: string
                    pattern: '^\d+\+?$'
                  image:
                    required: [repoTag]
                    properties:
                      repoTag:
                        type: string
                        minLength: 1
                  setup_package:
                    required: [config_api_version, import_url]
                    properties:
                      config_api_version:
                        type: integer
                        minimum: 7
                      import_url:
                        type: string
                        pattern: '^https?://.+\.tgz$'
            config:
              required: [selected_roles, role_services]
              properties:
                config_meta:
                  type: object
                selected_roles:
                  type: array
                  items:
                    type: string
                    minLength: 1
                role_services:
                  type: array
                  items:
                    required: [role_id, service_ids]
                    properties:
                      role_id:
                        type: string
                        minLength: 1
                      service_ids:
                        type: array
                        items:
                          type: string
                          minLength: 1
            persist_dirs:
              type: array
              items:
                type: string
                pattern: '^/[^/]+$'
            capabilities:
              type: array
              items:
                type: string
                minLength: 1
            systemdRequired:
              type: boolean
