kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "kubedirector.fullname" . }}
  labels:
    app: {{ template "kubedirector.name" . }}
    chart: {{ template "kubedirector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups:
  - kubedirector.bluedata.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - pods/exec
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - "get"
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - "get"
  - "create"

---
kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.serviceAccount.name}}

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "kubedirector.fullname" . }}
  labels:
    app: {{ template "kubedirector.name" . }}
    chart: {{ template "kubedirector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ template "kubedirector.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "kubedirector.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
