#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: ldapauthentication
#  labels:
#    kubedirector.hpe.com/cmType : ldap_config
#data:
## auth_type options are LDAP/Active Directory
#  auth_type: "Active Directory"
#  ssl_enabled: "False"
## use ',' as a delimiter to provide multiple server_address
#  server_address: "10.10.10.100,10.10.10.101"
#  ssl_enabled: "False"
#  server_port: "389"
#  lookup_dn: "True"
#  user_search_base: "ou=people,dc=wikimedia,dc=org"
#  user_attribute: "cn"
#  bind_user_dn: "cn=admin,ou=people,dc=wikimedia,dc=org"
##  #optional parameter. "use ":" as a delimiter to provide multiple templates"
#  bind_dn_template: "cn={username},ou=People,ou=people,dc=wikimedia,dc=org"
#  valid_username_regex: "^[A-Za-z][.@A-Za-z0-9_-]*$"
##  "use ":" as a delimiter to provide multiple member_of"
#  member_of: CN=Eng,OU=Engineering,ou=people,dc=wikimedia,dc=org:CN=QA,OU=Engineering,ou=people,dc=wikimedia,dc=org
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: ldapsecret
#  labels:
#    kubedirector.hpe.com/secretType : ldap_secret
#type: Opaque
#data:
## secret value is updated with base64 encoded
#  bind_user_password: YWRtaW4xMjMK
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: notebookusersecret
#  labels:
#    kubedirector.hpe.com/secretType : notebookusersecret
#type: Opaque
#data:
## secret values are updated with base64 encoded
#  notebook_username: YWRtaW4K
#  notebook_password: YWRtaW4xMjMK
#---
apiVersion: "kubedirector.hpe.com/v1beta1"
kind: "KubeDirectorCluster"
metadata:
  name: "spark245-instance"
spec:
  app: spark245
#  connections:
#    configmaps:
#    - ldapauthentication
#    secrets:
#    - ldapsecret
#    - notebookusersecret
  roles:
  - id: spark-master
    resources:
      requests:
        memory: "4Gi"
        cpu: "2"
      limits:
        memory: "4Gi"
        cpu: "2"
  - id: livy-server
    members: 1
    resources:
      requests:
        memory: "4Gi"
        cpu: "2"
      limits:
        memory: "4Gi"
        cpu: "2"
  - id: spark-worker
    members: 1
    resources:
      requests:
        memory: "4Gi"
        cpu: "2"
      limits:
        memory: "4Gi"
        cpu: "2"
  - id: notebook-server
    members: 1
    resources:
      requests:
        memory: "4Gi"
        cpu: "2"
      limits:
        memory: "4Gi"
        cpu: "2"