// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/bluek8s/kubedirector/pkg/apis/kubedirector.bluedata.io/v1alpha1.KubeDirectorApp":           schema_pkg_apis_kubedirector_v1alpha1_KubeDirectorApp(ref),
		"github.com/bluek8s/kubedirector/pkg/apis/kubedirector.bluedata.io/v1alpha1.KubeDirectorAppSpec":       schema_pkg_apis_kubedirector_v1alpha1_KubeDirectorAppSpec(ref),
		"github.com/bluek8s/kubedirector/pkg/apis/kubedirector.bluedata.io/v1alpha1.KubeDirectorAppStatus":     schema_pkg_apis_kubedirector_v1alpha1_KubeDirectorAppStatus(ref),
		"github.com/bluek8s/kubedirector/pkg/apis/kubedirector.bluedata.io/v1alpha1.KubeDirectorCluster":       schema_pkg_apis_kubedirector_v1alpha1_KubeDirectorCluster(ref),
		"github.com/bluek8s/kubedirector/pkg/apis/kubedirector.bluedata.io/v1alpha1.KubeDirectorClusterSpec":   schema_pkg_apis_kubedirector_v1alpha1_KubeDirectorClusterSpec(ref),
		"github.com/bluek8s/kubedirector/pkg/apis/kubedirector.bluedata.io/v1alpha1.KubeDirectorClusterStatus": schema_pkg_apis_kubedirector_v1alpha1_KubeDirectorClusterStatus(ref),
		"github.com/bluek8s/kubedirector/pkg/apis/kubedirector.bluedata.io/v1alpha1.KubeDirectorConfig":        schema_pkg_apis_kubedirector_v1alpha1_KubeDirectorConfig(ref),
		"github.com/bluek8s/kubedirector/pkg/apis/kubedirector.bluedata.io/v1alpha1.KubeDirectorConfigSpec":    schema_pkg_apis_kubedirector_v1alpha1_KubeDirectorConfigSpec(ref),
		"github.com/bluek8s/kubedirector/pkg/apis/kubedirector.bluedata.io/v1alpha1.KubeDirectorConfigStatus":  schema_pkg_apis_kubedirector_v1alpha1_KubeDirectorConfigStatus(ref),
	}
}

func schema_pkg_apis_kubedirector_v1alpha1_KubeDirectorApp(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KubeDirectorApp is the Schema for the kubedirectorapps API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/bluek8s/kubedirector/pkg/apis/kubedirector.bluedata.io/v1alpha1.KubeDirectorAppSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/bluek8s/kubedirector/pkg/apis/kubedirector.bluedata.io/v1alpha1.KubeDirectorAppStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/bluek8s/kubedirector/pkg/apis/kubedirector.bluedata.io/v1alpha1.KubeDirectorAppSpec", "github.com/bluek8s/kubedirector/pkg/apis/kubedirector.bluedata.io/v1alpha1.KubeDirectorAppStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_kubedirector_v1alpha1_KubeDirectorAppSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KubeDirectorAppSpec defines the desired state of KubeDirectorApp",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_kubedirector_v1alpha1_KubeDirectorAppStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KubeDirectorAppStatus defines the observed state of KubeDirectorApp",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_kubedirector_v1alpha1_KubeDirectorCluster(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KubeDirectorCluster is the Schema for the kubedirectorclusters API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/bluek8s/kubedirector/pkg/apis/kubedirector.bluedata.io/v1alpha1.KubeDirectorClusterSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/bluek8s/kubedirector/pkg/apis/kubedirector.bluedata.io/v1alpha1.KubeDirectorClusterStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/bluek8s/kubedirector/pkg/apis/kubedirector.bluedata.io/v1alpha1.KubeDirectorClusterSpec", "github.com/bluek8s/kubedirector/pkg/apis/kubedirector.bluedata.io/v1alpha1.KubeDirectorClusterStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_kubedirector_v1alpha1_KubeDirectorClusterSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KubeDirectorClusterSpec defines the desired state of KubeDirectorCluster",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_kubedirector_v1alpha1_KubeDirectorClusterStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KubeDirectorClusterStatus defines the observed state of KubeDirectorCluster",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_kubedirector_v1alpha1_KubeDirectorConfig(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KubeDirectorConfig is the Schema for the kubedirectorconfigs API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/bluek8s/kubedirector/pkg/apis/kubedirector.bluedata.io/v1alpha1.KubeDirectorConfigSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/bluek8s/kubedirector/pkg/apis/kubedirector.bluedata.io/v1alpha1.KubeDirectorConfigStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/bluek8s/kubedirector/pkg/apis/kubedirector.bluedata.io/v1alpha1.KubeDirectorConfigSpec", "github.com/bluek8s/kubedirector/pkg/apis/kubedirector.bluedata.io/v1alpha1.KubeDirectorConfigStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_kubedirector_v1alpha1_KubeDirectorConfigSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KubeDirectorConfigSpec defines the desired state of KubeDirectorConfig",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_kubedirector_v1alpha1_KubeDirectorConfigStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KubeDirectorConfigStatus defines the observed state of KubeDirectorConfig",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
